{% set name = "polars-distance" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polars_distance-{{ version }}.tar.gz
    sha256: 26b7fbfc38de1c81b847ffa87b4f106dd10d4585a2240fff882e0f1fcb1acad8
  - url: https://raw.githubusercontent.com/ion-elgreco/polars-distance/main/LICENSE
    sha256: 017feb4ae87126410f1d9beb6af4c9df3c25a0051d87db66da6f26c509f5348d

build:
  number: 1
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - polars >=0.20.16

test:
  imports:
    - polars_distance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ion-elgreco/polars-distance
  summary: Polars plugin for pairwise distance functions
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
