{% set name = "polars-distance" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars_distance-{{ version }}.tar.gz
    sha256: a622d3d772c0d35be3d385d3c45f97b870349c05744f9eb6461afb03291657e6
  - url: https://raw.githubusercontent.com/ion-elgreco/polars-distance/main/LICENSE
    sha256: 017feb4ae87126410f1d9beb6af4c9df3c25a0051d87db66da6f26c509f5348d

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - polars >=0.20.16

test:
  imports:
    - polars_distance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ion-elgreco/polars-distance
  summary: Polars plugin for pairwise distance functions
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
